spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/test
    username: amold
    password: amold123
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub