spring.application.name=orm-learn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=amold
spring.datasource.password=amold123
spring.datasource.url=jdbc:postgresql://localhost:5431/sanctury
spring.jpa.hibernate.ddl-auto=update



logging.level.org.springframework = info
logging.level.in.amold.ormlearn=debug
logging.pattern.console=%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n