spring.application.name=DataJPARelations
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5431/test
spring.datasource.username=amold
spring.datasource.password=amold123
