spring.application.name=account
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5431/accounts?options=-c%20timezone=UTC
spring.datasource.username=amold
spring.datasource.password=amold123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

