spring.application.name=Spring-Rest2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.datasource.username=amold
spring.datasource.password=amold123
spring.datasource.url=jdbc:postgresql://localhost:5431/test
logging.level.in.amold.springrest2=DEBUG
logging.level.in.amold=TRACE